### ISSUE TITLE
In asymmetric matrices the column sort indices all default to 1.0

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#10]
The column sort indices should default to incrementing numbers.  Not sure what happens if you press the sort button with them all equal (I didn't try that).

**Comment by ajcarney** [comment]
Is this when creating a new matrix, converting a symmetric matrix, or both? Does pressing the redistribute sort indexes button work as a temporary fix?

**Comment by dtcarney741** [comment]
When adding rows and columns to a non-symmetric matrix, the columns get the index of the row before them plus 1.  So if you enter all the columns and then all the rows, they are all 1.  If you enter all the rows and then the columns all indices are last row + 1.  If you intersperse rows and columns they increment like you expect.

Pressing re-distribute sort indices button does renumber them correctly. (Note the button says Re-Distribute Sort Indexes, and should say Re-Distribute Sort Indices which is the proper plural of index).

Pressing sort when multiple rows or columns have the same index value has no effect, which is good.

**Comment by ajcarney** [comment]
Fixed. I'll close this issue once I tag a release after the other features are added.

(Note: [indexes is an acceptable usage of the plural of index, however, I did change it because indices is "generally preferred" in technical applications](https://grammarist.com/usage/indexes-indices/)
