### ISSUE TITLE
Transpose function

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#13]
The tool needs a function to transpose symmetric matrices. Process DSMs can be represented two ways:
IR / FAD (inputs in rows, feedback above diagonal)
IC / FBD (inputs in columns, feedback below diagonal)

The two are related by a simple matrix transpose. The tool should support a transpose function. It should also have a text fields for DSM description (Title, Project Name, Customer, Version, ...) added as follows:
DSM Type (A user could put in something like "Process DSM - IR/FAD")

**Comment by ajcarney** [comment]
Could you confirm if the invert matrix function under the edit menu for symmetrical matrices is the functionality for that part of the requirement you are looking for
