### ISSUE TITLE
Font Color Editing

### ISSUE THREAD

**Issue by edgarsolano** [ajcarney/DSMEditor#18]
Hello.  This tool is awesome.  I have a quality of life improvement suggestion.  I noticed when assigning colors with the configure grouping function some of the darker shades make black text difficult to read. If we could change the font color to a light gray would be helpful.  Thanks.  
![image](https://user-images.githubusercontent.com/95925946/145595989-754df0e5-2de2-4606-8a06-8032618fbad2.png)

**Comment by ajcarney** [comment]
The development for this is complete and this feature and a bunch of others will be there in the next major release (hopefully mid-July but early August at the absolute latest). I implemented it by adding an additional color picker for the font color on the configure groupings window.

**Comment by ajcarney** [comment]
Release is out now, closing this issue

**Comment by edgarsolano** [comment]
Hello,

Excellent! Thanks for the update. Looking forward to the next release.

Sincerely,


Edgar Solano II
Senior Staff Engineer - Systems
+1 919 807 8127 Direct
+1 910 988 0256 Mobile
