### ISSUE TITLE
Editing row/column names in place

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#19]
It would be nice if row/column names could be edited just by clicking on the name and then typing over what is already there. It could be in a pop up window if that is easier. It's cumbersome to choose the rename row/column button, select the one you want and then you have to retype the whole name if you just want to make a minor change to the name.

**Comment by dtcarney741** [comment]
I have mostly implemented this code on the branch "new features". The only things that needs to be done is to get rid of the button to rename matrix items since it is not needed anymore, and to fix a bug with screen updating. If you edit the row item of a symmetric matrix, the corresponding column item also gets updated, but the screen does not refresh, so it looks like the row name changed but not the column name. Any GUI action that refreshes the screen after this will fix the display (ie zooming in and out).

**Comment by ajcarney** [comment]
I took a lot of your code but refactored it a little and merged it into the major refactor. I also fixed all the bugs you had when you developed it. It will be there in the next major release. It is still implemented such that when you click on an item a window opens to let you rename it
