### ISSUE TITLE
propagation exclusions

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#5]
The propagation exclusions do not seem to be working quite right.  When I select to analyze propagation from an item in a group, and then add exclusions to the other items within that group that have connections outside the group, I expect that nothing outside the group should show up on the propagation analysis.  Maybe that's not the right expectation.  I need to understand how this is working better and then decide if that is how I want it to work, or it needs to be changed.

**Comment by ajcarney** [comment]
Currently, propagation analysis does not respect groupings at all. The exclusions work by if an item is found to be connected to another item, then it is counted in the results, but its connections are not added to the next level if it is excluded. Do you want a feature to only run the analysis for the start items grouping, or should this be the default behavior?

**Comment by ajcarney** [comment]
[fixed](https://github.com/ajcarney/DSMEditor/commit/03834c6e5afcf6ef034775f35e622864177c950e)
The issue occurred when checking for exclusions; it would compare the alias for the column and not the actual id of the column so it would appear that the connection was not listed in the exclusions. This fix will be present in the next release (hopefully soon).
