### ISSUE TITLE
Feature Request - implement Thebeau clustering algorithm

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#6]
Ronnie Thebeau published a clustering algorithm for design structure matrices in his Masters Thesis at MIT in 2001.  Here is a link to a description and implementation of that code:

https://dsmweb.org/matlab-macro-for-clustering-dsms/

Port this algorithm to this editor program.  I have attempted to use the algorithm and for many real system designs it results in too granular of groupings.  The goal is to modify the algorithm so that the groupings are larger to create more realistic optimal subsystems in real system architectures.  Having a better user interface to running the algorithm will help identify these improvements.

**Comment by ajcarney** [comment]
Is this separate from the propagation analysis or does it replace the current propagation analysis, and as such should have its own GUI window?

**Comment by ajcarney** [comment]
[Added](https://github.com/ajcarney/DSMEditor/commit/c27626181aa1cac1314645fd5955cc728f01274e)
This contains the constant subtracted from the exponential constants that penalize cluster size. I also added the option to set the seed for the trial for more repeatable results. 

I have yet to test it with the original DSM from the paper and see how this implementation compares.

This feature will be included in the next release.
