### ISSUE TITLE
Delete grouping does not work

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#7]
The delete grouping function does not seem to do anything.  After deleting a grouping it disappears from the Configure Groupings window, but it is still present, and if you close and reopen Configure Groupings it is back.

**Comment by ajcarney** [comment]
I fixed this in the latest commit. I'll tag a release soon and then close the issue.

**Comment by ajcarney** [comment]
I'm going to close this issue because it is fixed in the latest release (v1.2.2). Reopen it if you find the issue persists
