### ISSUE TITLE
Feature Request - matrix inversion

### ISSUE THREAD

**Issue by dtcarney741** [ajcarney/DSMEditor#9]
Swap the rows and columns.  This is useful even for symmetric DSMs when using a symmetric DSM as a process diagram so you can quickly switch the inputs and outputs relationships.

**Comment by ajcarney** [comment]
Should this swap the connection row and columns as well, where if a connection is from A to B, the new connection is from B to A? Or does the connection stay with the A that was a column and is now a row?

**Comment by dtcarney741** [comment]
I mean transpose, not inversion.  The connection stays with the A that was a column and is now a row.
I'm attaching a very simple DSM and its transpose as an example.
[simple_dsms.zip](https://github.com/ajcarney/DSMEditor/files/7145090/simple_dsms.zip)

**Comment by ajcarney** [comment]
Added and included in the release. It appeared to work correctly for both symmetric and non-symmetric dsms
